---
RSpecRails:
  Enabled: true
  DocumentationBaseURL: https://docs.rubocop.org/rubocop-rspec_rails
  Include:
    - "**/*_spec.rb"
    - "**/spec/**/*"

RSpecRails/AvoidSetupHook:
  Description: Prefer RSpec `before` hook over Rails `setup` method.
  Enabled: pending
  VersionAdded: '2.4'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/AvoidSetupHook

RSpecRails/HaveHttpStatus:
  Description: Prefer `have_http_status` over equality matchers.
  Enabled: pending
  ResponseMethods:
    - response
    - last_response
  SafeAutoCorrect: false
  VersionAdded: '2.12'
  VersionChanged: '2.27'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/HaveHttpStatus

RSpecRails/HttpStatus:
  Description: Enforce use of symbolic or numeric value to describe HTTP status.
  Enabled: true
  EnforcedStyle: symbolic
  SupportedStyles:
    - numeric
    - symbolic
    - be_status
  VersionAdded: '1.23'
  VersionChanged: '2.20'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/HttpStatus

RSpecRails/HttpStatusNameConsistency:
  Description: Enforce consistency by using the current HTTP status names.
  Enabled: pending
  VersionAdded: '2.32'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/HttpStatusNameConsistency

RSpecRails/InferredSpecType:
  Description: Identify redundant spec type.
  Enabled: pending
  Safe: false
  VersionAdded: '2.14'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/InferredSpecType
  Inferences:
    channels: channel
    controllers: controller
    features: feature
    generator: generator
    helpers: helper
    jobs: job
    mailboxes: mailbox
    mailers: mailer
    models: model
    requests: request
    integration: request
    api: request
    routing: routing
    system: system
    views: view

RSpecRails/MinitestAssertions:
  Description: Prefer RSpec/Rails-style matchers over Minitest-like matchers.
  Enabled: pending
  VersionAdded: '2.17'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/MinitestAssertions

RSpecRails/NegationBeValid:
  Description: Enforce use of `be_invalid` or `not_to` for negated be_valid.
  AutoCorrect: contextual
  Safe: false
  EnforcedStyle: not_to
  SupportedStyles:
    - not_to
    - be_invalid
  Enabled: pending
  VersionAdded: '2.23'
  VersionChanged: '2.29'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/NegationBeValid

RSpecRails/ReceivePerformLater:
  Description: Prefer `have_enqueued_job` over `receive(:perform_later)`.
  Enabled: pending
  VersionAdded: '2.33'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/ReceivePerformLater

RSpecRails/TravelAround:
  Description: Prefer to travel in `before` rather than `around`.
  Enabled: pending
  Safe: false
  VersionAdded: '2.19'
  Reference: https://www.rubydoc.info/gems/rubocop-rspec_rails/RuboCop/Cop/RSpecRails/TravelAround
